/**
 * Hardware for the VRAM Estimator: what each device's driver reports (or, for
 * unified memory, what the GPU may use by default), from vendor spec pages and
 * published nvidia-smi / rocm-smi output. Researched 2026-10-06; rows marked
 * "derived" come from a sibling SKU's driver output, "estimate" are unconfirmed.
 *
 * Units: usableGiB is binary (2^30 bytes); memoryGb is the marketed figure.
 * An RTX 4090 reports 23.99 GiB; a B200 sold as "192 GB" reports 179.06 GiB.
 */

export interface Device {
  id: string;
  name: string;
  short: string;
  vendor: "nvidia" | "amd" | "apple" | "intel";
  cls: "consumer" | "workstation" | "datacenter" | "unified";
  /** Marketed capacity. */
  memoryGb: number;
  /** Driver-reported total, or the default GPU allocation on unified memory, in GiB. */
  usableGiB: number;
  basis: string;
  bandwidthGBs: number;
  year: number;
  status: string;
  /** Unified memory: total RAM (for the raised macOS cap). */
  ramGiB?: number;
  /** Unified memory: the ceiling after tuning. */
  maxGiB?: number;
  /** Blackwell or newer (NVFP4). */
  blackwell?: boolean;
  /** In the short default list. */
  isDefault?: boolean;
  note?: string;
  verified: string;
  source: string;
}

export const DEVICES_CHECKED = "2026-10-06";

export const DEVICES: readonly Device[] = [
  {
    "id": "rtx-3060-12gb",
    "name": "GeForce RTX 3060 12GB",
    "short": "RTX 3060 12GB",
    "vendor": "nvidia",
    "cls": "consumer",
    "memoryGb": 12,
    "usableGiB": 12.0,
    "basis": "derived",
    "bandwidthGBs": 360,
    "year": 2021,
    "status": "prev-gen",
    "isDefault": true,
    "verified": "partial",
    "source": "https://www.notebookcheck.net/NVIDIA-GeForce-RTX-3060-vs-NVIDIA-GeForce-RTX-3080-12-GB_10960_11367.247598.0.html"
  },
  {
    "id": "rtx-3080-10gb",
    "name": "GeForce RTX 3080 10GB",
    "short": "RTX 3080 10GB",
    "vendor": "nvidia",
    "cls": "consumer",
    "memoryGb": 10,
    "usableGiB": 10.0,
    "basis": "derived",
    "bandwidthGBs": 760,
    "year": 2020,
    "status": "prev-gen",
    "verified": "partial",
    "source": "https://www.techpowerup.com/271497/nvidia-geforce-rtx-3090-and-3080-specifications-leaked"
  },
  {
    "id": "rtx-3080-12gb",
    "name": "GeForce RTX 3080 12GB",
    "short": "RTX 3080 12GB",
    "vendor": "nvidia",
    "cls": "consumer",
    "memoryGb": 12,
    "usableGiB": 12.0,
    "basis": "derived",
    "bandwidthGBs": 912,
    "year": 2022,
    "status": "prev-gen",
    "verified": "partial",
    "source": "https://www.notebookcheck.net/NVIDIA-GeForce-RTX-3060-vs-NVIDIA-GeForce-RTX-3080-12-GB_10960_11367.247598.0.html"
  },
  {
    "id": "rtx-3090",
    "name": "GeForce RTX 3090",
    "short": "RTX 3090",
    "vendor": "nvidia",
    "cls": "consumer",
    "memoryGb": 24,
    "usableGiB": 24.0,
    "basis": "smi",
    "bandwidthGBs": 936,
    "year": 2020,
    "status": "prev-gen",
    "isDefault": true,
    "note": "nvidia-smi 24576MiB",
    "verified": "partial",
    "source": "https://www.thefpsreview.com/gpu-family/nvidia-geforce-rtx-3090-gpu-family-specifications/"
  },
  {
    "id": "rtx-3090-ti",
    "name": "GeForce RTX 3090 Ti",
    "short": "RTX 3090 Ti",
    "vendor": "nvidia",
    "cls": "consumer",
    "memoryGb": 24,
    "usableGiB": 24.0,
    "basis": "derived",
    "bandwidthGBs": 1008,
    "year": 2022,
    "status": "prev-gen",
    "verified": "partial",
    "source": "https://www.techspot.com/specs/gpu/247286-nvidia-geforce-rtx-3090-ti.html"
  },
  {
    "id": "rtx-4060-8gb",
    "name": "GeForce RTX 4060",
    "short": "RTX 4060",
    "vendor": "nvidia",
    "cls": "consumer",
    "memoryGb": 8,
    "usableGiB": 7.99,
    "basis": "derived",
    "bandwidthGBs": 272,
    "year": 2023,
    "status": "prev-gen",
    "verified": "partial",
    "source": "https://www.techspot.com/review/2701-nvidia-geforce-rtx-4060/"
  },
  {
    "id": "rtx-4060-ti-16gb",
    "name": "GeForce RTX 4060 Ti 16GB",
    "short": "RTX 4060 Ti 16GB",
    "vendor": "nvidia",
    "cls": "consumer",
    "memoryGb": 16,
    "usableGiB": 16.0,
    "basis": "derived",
    "bandwidthGBs": 288,
    "year": 2023,
    "status": "prev-gen",
    "verified": "partial",
    "source": "https://www.cgchannel.com/2024/08/group-test-nvidia-geforce-rtx-40-series-and-super-series-gpus/"
  },
  {
    "id": "rtx-4070-ti-super",
    "name": "GeForce RTX 4070 Ti SUPER",
    "short": "RTX 4070 Ti SUPER",
    "vendor": "nvidia",
    "cls": "consumer",
    "memoryGb": 16,
    "usableGiB": 15.99,
    "basis": "derived",
    "bandwidthGBs": 672,
    "year": 2024,
    "status": "prev-gen",
    "verified": "partial",
    "source": "https://www.techpowerup.com/317479/nvidia-announces-the-geforce-rtx-40-super-series-graphics-cards"
  },
  {
    "id": "rtx-4080",
    "name": "GeForce RTX 4080",
    "short": "RTX 4080",
    "vendor": "nvidia",
    "cls": "consumer",
    "memoryGb": 16,
    "usableGiB": 15.99,
    "basis": "derived",
    "bandwidthGBs": 717,
    "year": 2022,
    "status": "prev-gen",
    "verified": "partial",
    "source": "https://www.cgchannel.com/2024/08/group-test-nvidia-geforce-rtx-40-series-and-super-series-gpus/"
  },
  {
    "id": "rtx-4080-super",
    "name": "GeForce RTX 4080 SUPER",
    "short": "RTX 4080 SUPER",
    "vendor": "nvidia",
    "cls": "consumer",
    "memoryGb": 16,
    "usableGiB": 15.99,
    "basis": "derived",
    "bandwidthGBs": 736,
    "year": 2024,
    "status": "prev-gen",
    "verified": "partial",
    "source": "https://www.techpowerup.com/317479/nvidia-announces-the-geforce-rtx-40-super-series-graphics-cards"
  },
  {
    "id": "rtx-4090",
    "name": "GeForce RTX 4090",
    "short": "RTX 4090",
    "vendor": "nvidia",
    "cls": "consumer",
    "memoryGb": 24,
    "usableGiB": 23.99,
    "basis": "smi",
    "bandwidthGBs": 1008,
    "year": 2022,
    "status": "prev-gen",
    "isDefault": true,
    "note": "nvidia-smi 24564MiB",
    "verified": "partial",
    "source": "https://www.tomshardware.com/features/nvidia-ada-lovelace-and-geforce-rtx-40-series-everything-we-know"
  },
  {
    "id": "rtx-5060-8gb",
    "name": "GeForce RTX 5060",
    "short": "RTX 5060",
    "vendor": "nvidia",
    "cls": "consumer",
    "memoryGb": 8,
    "usableGiB": 7.96,
    "basis": "derived",
    "bandwidthGBs": 448,
    "year": 2025,
    "status": "shipping",
    "blackwell": true,
    "note": "128-bit 28Gbps",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/rtx-5060-family/"
  },
  {
    "id": "rtx-5060-ti-16gb",
    "name": "GeForce RTX 5060 Ti 16GB",
    "short": "RTX 5060 Ti 16GB",
    "vendor": "nvidia",
    "cls": "consumer",
    "memoryGb": 16,
    "usableGiB": 15.92,
    "basis": "derived",
    "bandwidthGBs": 448,
    "year": 2025,
    "status": "shipping",
    "blackwell": true,
    "isDefault": true,
    "note": "128-bit 28Gbps; represents the 16GB tier",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/rtx-5060-family/"
  },
  {
    "id": "rtx-5070",
    "name": "GeForce RTX 5070",
    "short": "RTX 5070",
    "vendor": "nvidia",
    "cls": "consumer",
    "memoryGb": 12,
    "usableGiB": 11.94,
    "basis": "derived",
    "bandwidthGBs": 672,
    "year": 2025,
    "status": "shipping",
    "blackwell": true,
    "note": "192-bit",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/rtx-5070-family/"
  },
  {
    "id": "rtx-5070-ti",
    "name": "GeForce RTX 5070 Ti",
    "short": "RTX 5070 Ti",
    "vendor": "nvidia",
    "cls": "consumer",
    "memoryGb": 16,
    "usableGiB": 15.92,
    "basis": "smi",
    "bandwidthGBs": 896,
    "year": 2025,
    "status": "shipping",
    "blackwell": true,
    "note": "nvidia-smi 16303MiB (single report)",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/rtx-5070-family/"
  },
  {
    "id": "rtx-5080",
    "name": "GeForce RTX 5080",
    "short": "RTX 5080",
    "vendor": "nvidia",
    "cls": "consumer",
    "memoryGb": 16,
    "usableGiB": 15.92,
    "basis": "derived",
    "bandwidthGBs": 960,
    "year": 2025,
    "status": "shipping",
    "blackwell": true,
    "verified": "partial",
    "source": "https://www.tomshardware.com/pc-components/gpus/nvidia-blackwell-rtx-50-series-gpus-everything-we-know"
  },
  {
    "id": "rtx-5090",
    "name": "GeForce RTX 5090",
    "short": "RTX 5090",
    "vendor": "nvidia",
    "cls": "consumer",
    "memoryGb": 32,
    "usableGiB": 31.84,
    "basis": "smi",
    "bandwidthGBs": 1792,
    "year": 2025,
    "status": "shipping",
    "blackwell": true,
    "isDefault": true,
    "note": "512-bit; nvidia-smi 32607MiB",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/rtx-5090/"
  },
  {
    "id": "rtx-a6000",
    "name": "RTX A6000",
    "short": "RTX A6000",
    "vendor": "nvidia",
    "cls": "workstation",
    "memoryGb": 48,
    "usableGiB": 47.99,
    "basis": "derived",
    "bandwidthGBs": 768,
    "year": 2020,
    "status": "prev-gen",
    "note": "~44.99 GiB with ECC on",
    "verified": "vendor",
    "source": "https://www.nvidia.com/content/dam/en-zz/Solutions/design-visualization/quadro-product-literature/proviz-print-nvidia-rtx-a6000-datasheet-us-nvidia-1454980-r9-web%20(1).pdf"
  },
  {
    "id": "rtx-6000-ada",
    "name": "RTX 6000 Ada Generation",
    "short": "RTX 6000 Ada",
    "vendor": "nvidia",
    "cls": "workstation",
    "memoryGb": 48,
    "usableGiB": 47.99,
    "basis": "smi",
    "bandwidthGBs": 960,
    "year": 2022,
    "status": "prev-gen",
    "note": "49140MiB ECC off; 46068MiB (44.99 GiB) ECC on",
    "verified": "vendor",
    "source": "https://www.nvidia.com/content/dam/en-zz/Solutions/design-visualization/rtx-6000/proviz-print-rtx6000-datasheet-web-2504660.pdf"
  },
  {
    "id": "rtx-pro-2000-blackwell",
    "name": "RTX PRO 2000 Blackwell",
    "short": "RTX PRO 2000 Blackwell",
    "vendor": "nvidia",
    "cls": "workstation",
    "memoryGb": 16,
    "usableGiB": 15.93,
    "basis": "derived",
    "bandwidthGBs": 288,
    "year": 2025,
    "status": "shipping",
    "blackwell": true,
    "note": "bandwidth not confirmed on NVIDIA page",
    "verified": "partial",
    "source": "https://www.nvidia.com/en-us/products/workstations/professional-desktop-gpus/"
  },
  {
    "id": "rtx-pro-4000-blackwell",
    "name": "RTX PRO 4000 Blackwell",
    "short": "RTX PRO 4000 Blackwell",
    "vendor": "nvidia",
    "cls": "workstation",
    "memoryGb": 24,
    "usableGiB": 23.9,
    "basis": "derived",
    "bandwidthGBs": 672,
    "year": 2025,
    "status": "shipping",
    "blackwell": true,
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/products/workstations/professional-desktop-gpus/rtx-pro-4000/"
  },
  {
    "id": "rtx-pro-4000-sff-blackwell",
    "name": "RTX PRO 4000 Blackwell SFF",
    "short": "RTX PRO 4000 Blackwell SFF",
    "vendor": "nvidia",
    "cls": "workstation",
    "memoryGb": 24,
    "usableGiB": 23.9,
    "basis": "derived",
    "bandwidthGBs": 432,
    "year": 2025,
    "status": "shipping",
    "blackwell": true,
    "note": "bandwidth not confirmed on NVIDIA page",
    "verified": "partial",
    "source": "https://www.nvidia.com/en-us/products/workstations/professional-desktop-gpus/"
  },
  {
    "id": "rtx-pro-4500-blackwell",
    "name": "RTX PRO 4500 Blackwell",
    "short": "RTX PRO 4500 Blackwell",
    "vendor": "nvidia",
    "cls": "workstation",
    "memoryGb": 32,
    "usableGiB": 31.86,
    "basis": "derived",
    "bandwidthGBs": 896,
    "year": 2025,
    "status": "shipping",
    "blackwell": true,
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/products/workstations/professional-desktop-gpus/rtx-pro-4500/"
  },
  {
    "id": "rtx-pro-5000-blackwell-48gb",
    "name": "RTX PRO 5000 Blackwell 48GB",
    "short": "RTX PRO 5000 Blackwell 48GB",
    "vendor": "nvidia",
    "cls": "workstation",
    "memoryGb": 48,
    "usableGiB": 47.8,
    "basis": "derived",
    "bandwidthGBs": 1344,
    "year": 2025,
    "status": "shipping",
    "blackwell": true,
    "note": "384-bit",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/products/workstations/professional-desktop-gpus/rtx-pro-5000/"
  },
  {
    "id": "rtx-pro-5000-blackwell-72gb",
    "name": "RTX PRO 5000 Blackwell 72GB",
    "short": "RTX PRO 5000 Blackwell 72GB",
    "vendor": "nvidia",
    "cls": "workstation",
    "memoryGb": 72,
    "usableGiB": 71.69,
    "basis": "derived",
    "bandwidthGBs": 1344,
    "year": 2025,
    "status": "shipping",
    "blackwell": true,
    "note": "GA 2025-12-20",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/products/workstations/professional-desktop-gpus/rtx-pro-5000/"
  },
  {
    "id": "rtx-pro-6000-blackwell",
    "name": "RTX PRO 6000 Blackwell Workstation Edition",
    "short": "RTX PRO 6000 Blackwell",
    "vendor": "nvidia",
    "cls": "workstation",
    "memoryGb": 96,
    "usableGiB": 95.59,
    "basis": "smi",
    "bandwidthGBs": 1792,
    "year": 2025,
    "status": "shipping",
    "blackwell": true,
    "isDefault": true,
    "note": "nvidia-smi 97887MiB",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/products/workstations/professional-desktop-gpus/rtx-pro-6000/"
  },
  {
    "id": "rtx-pro-6000-blackwell-maxq",
    "name": "RTX PRO 6000 Blackwell Max-Q",
    "short": "RTX PRO 6000 Blackwell Max-Q",
    "vendor": "nvidia",
    "cls": "workstation",
    "memoryGb": 96,
    "usableGiB": 95.59,
    "basis": "derived",
    "bandwidthGBs": 1792,
    "year": 2025,
    "status": "shipping",
    "blackwell": true,
    "note": "300W",
    "verified": "vendor",
    "source": "https://www.nvidia.com/content/dam/en-zz/Solutions/products/workstations/professional-desktop-gpus/rtx-pro-6000-max-q/workstation-datasheet-blackwell-rtx-pro-6000-max-q-nvidia-3519233.pdf"
  },
  {
    "id": "rtx-pro-6000-blackwell-server",
    "name": "RTX PRO 6000 Blackwell Server Edition",
    "short": "RTX PRO 6000 Blackwell Server Edition",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 96,
    "usableGiB": 95.59,
    "basis": "derived",
    "bandwidthGBs": 1597,
    "year": 2025,
    "status": "shipping",
    "blackwell": true,
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/data-center/rtx-pro-6000-blackwell-server-edition/"
  },
  {
    "id": "t4",
    "name": "T4",
    "short": "T4",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 16,
    "usableGiB": 15.0,
    "basis": "smi",
    "bandwidthGBs": 320,
    "year": 2018,
    "status": "prev-gen",
    "note": "15360MiB with ECC on",
    "verified": "partial",
    "source": "https://thundergolfer.com/blog/nvidia-gpu-memory-capacity"
  },
  {
    "id": "a10g",
    "name": "A10G (AWS G5)",
    "short": "A10G (AWS G5)",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 24,
    "usableGiB": 22.49,
    "basis": "smi",
    "bandwidthGBs": 600,
    "year": 2021,
    "status": "rentable",
    "note": "A10 figures; AWS lists 24GB per A10G; ECC on",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/data-center/products/a10-gpu/"
  },
  {
    "id": "l4",
    "name": "L4",
    "short": "L4",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 24,
    "usableGiB": 22.49,
    "basis": "smi",
    "bandwidthGBs": 300,
    "year": 2023,
    "status": "shipping",
    "note": "23034MiB",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/data-center/l4/"
  },
  {
    "id": "a40",
    "name": "A40",
    "short": "A40",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 48,
    "usableGiB": 44.99,
    "basis": "derived",
    "bandwidthGBs": 696,
    "year": 2020,
    "status": "rentable",
    "note": "ECC on by default",
    "verified": "partial",
    "source": "https://www.nvidia.com/en-us/data-center/a40/"
  },
  {
    "id": "l40s",
    "name": "L40S",
    "short": "L40S",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 48,
    "usableGiB": 44.99,
    "basis": "smi",
    "bandwidthGBs": 864,
    "year": 2023,
    "status": "shipping",
    "isDefault": true,
    "note": "46068MiB with ECC on (default)",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/data-center/l40s/"
  },
  {
    "id": "a100-40gb",
    "name": "A100 40GB",
    "short": "A100 40GB",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 40,
    "usableGiB": 40.0,
    "basis": "smi",
    "bandwidthGBs": 1555,
    "year": 2020,
    "status": "rentable",
    "note": "PCIe and SXM",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/data-center/a100/"
  },
  {
    "id": "a100-80gb-pcie",
    "name": "A100 80GB PCIe",
    "short": "A100 80GB PCIe",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 80,
    "usableGiB": 80.0,
    "basis": "smi",
    "bandwidthGBs": 1935,
    "year": 2021,
    "status": "rentable",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/data-center/a100/"
  },
  {
    "id": "a100-80gb-sxm",
    "name": "A100 80GB SXM",
    "short": "A100 80GB SXM",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 80,
    "usableGiB": 80.0,
    "basis": "smi",
    "bandwidthGBs": 2039,
    "year": 2020,
    "status": "rentable",
    "isDefault": true,
    "note": "81920MiB",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/data-center/a100/"
  },
  {
    "id": "h100-pcie",
    "name": "H100 PCIe",
    "short": "H100 PCIe",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 80,
    "usableGiB": 79.65,
    "basis": "derived",
    "bandwidthGBs": 2000,
    "year": 2022,
    "status": "rentable",
    "verified": "vendor",
    "source": "https://www.nvidia.com/content/dam/en-zz/Solutions/gtcs22/data-center/h100/PB-11133-001_v01.pdf"
  },
  {
    "id": "h100-sxm",
    "name": "H100 SXM",
    "short": "H100 SXM",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 80,
    "usableGiB": 79.65,
    "basis": "smi",
    "bandwidthGBs": 3350,
    "year": 2022,
    "status": "rentable",
    "isDefault": true,
    "note": "81559MiB",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/data-center/h100/"
  },
  {
    "id": "h100-nvl",
    "name": "H100 NVL",
    "short": "H100 NVL",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 94,
    "usableGiB": 93.58,
    "basis": "smi",
    "bandwidthGBs": 3900,
    "year": 2023,
    "status": "rentable",
    "note": "95830MiB",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/data-center/h100/"
  },
  {
    "id": "h200-sxm",
    "name": "H200 SXM",
    "short": "H200 SXM",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 141,
    "usableGiB": 140.4,
    "basis": "smi",
    "bandwidthGBs": 4800,
    "year": 2024,
    "status": "rentable",
    "isDefault": true,
    "note": "143771MiB",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/data-center/h200/"
  },
  {
    "id": "h200-nvl",
    "name": "H200 NVL",
    "short": "H200 NVL",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 141,
    "usableGiB": 140.4,
    "basis": "derived",
    "bandwidthGBs": 4800,
    "year": 2024,
    "status": "rentable",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/data-center/h200/"
  },
  {
    "id": "gh200-96gb",
    "name": "GH200 Grace Hopper 96GB",
    "short": "GH200 Grace Hopper 96GB",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 96,
    "usableGiB": 95.58,
    "basis": "smi",
    "bandwidthGBs": 4000,
    "year": 2023,
    "status": "rentable",
    "note": "97871MiB; plus up to 480GB LPDDR5X CPU memory via NVLink-C2C",
    "verified": "vendor",
    "source": "https://www.amax.com/content/files/2023/12/NVIDIA_GH200_Grace_Hopper_Superchip_Datasheet.pdf"
  },
  {
    "id": "gh200-144gb",
    "name": "GH200 Grace Hopper 144GB",
    "short": "GH200 Grace Hopper 144GB",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 144,
    "usableGiB": 140.4,
    "basis": "derived",
    "bandwidthGBs": 4900,
    "year": 2024,
    "status": "rentable",
    "note": "usable unverified; bandwidth 4.8 or 4.9 TB/s across NVIDIA docs",
    "verified": "partial",
    "source": "https://www.nvidia.com/en-us/data-center/grace-hopper-superchip/"
  },
  {
    "id": "b200",
    "name": "B200 (HGX/DGX)",
    "short": "B200",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 192,
    "usableGiB": 179.06,
    "basis": "smi",
    "bandwidthGBs": 8000,
    "year": 2024,
    "status": "rentable",
    "blackwell": true,
    "isDefault": true,
    "note": "183359MiB; 192 is decimal GB; DGX B200 lists 1,440GB per 8 GPUs",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/data-center/dgx-b200/"
  },
  {
    "id": "gb200-gpu",
    "name": "GB200 (per Blackwell GPU)",
    "short": "GB200 (per Blackwell GPU)",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 186,
    "usableGiB": 185.03,
    "basis": "smi",
    "bandwidthGBs": 8000,
    "year": 2025,
    "status": "rack-only",
    "blackwell": true,
    "note": "189471MiB; 372GB per superchip",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/data-center/gb200-nvl72/"
  },
  {
    "id": "b300",
    "name": "B300 Blackwell Ultra (HGX/DGX)",
    "short": "B300",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 288,
    "usableGiB": 268.59,
    "basis": "smi",
    "bandwidthGBs": 8000,
    "year": 2025,
    "status": "rentable",
    "blackwell": true,
    "note": "275040MiB; 288 is decimal GB; DGX/HGX B300 list 2.1TB per 8 GPUs",
    "verified": "vendor",
    "source": "https://github.com/oracle-quickstart/oci-gpu-quickstarts/blob/main/nvidia/B300/README-B300.md"
  },
  {
    "id": "gb300-gpu",
    "name": "GB300 (per Blackwell Ultra GPU)",
    "short": "GB300 (per GPU)",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 288,
    "usableGiB": 268.59,
    "basis": "derived",
    "bandwidthGBs": 8000,
    "year": 2025,
    "status": "rack-only",
    "blackwell": true,
    "note": "assumed same as B300; consistent with 20.7TB per NVL72",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/data-center/gb300-nvl72/"
  },
  {
    "id": "rubin-gpu",
    "name": "Rubin (per GPU)",
    "short": "Rubin (per GPU)",
    "vendor": "nvidia",
    "cls": "datacenter",
    "memoryGb": 288,
    "usableGiB": 250,
    "basis": "estimate",
    "bandwidthGBs": 22000,
    "year": 2026,
    "status": "rack-only",
    "blackwell": true,
    "note": "usable unverified; HGX Rubin NVL8 lists 2TB per 8 GPUs; NVL72 racks shipping since Sep 2026",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/data-center/hgx/"
  },
  {
    "id": "dgx-station-gb300",
    "name": "DGX Station GB300 (GPU HBM tier)",
    "short": "DGX Station GB300 (GPU HBM tier)",
    "vendor": "nvidia",
    "cls": "workstation",
    "memoryGb": 252,
    "usableGiB": 235,
    "basis": "estimate",
    "bandwidthGBs": 7100,
    "year": 2026,
    "status": "shipping",
    "blackwell": true,
    "note": "plus 496GB LPDDR5X at 396GB/s, 748GB coherent; usable unverified",
    "verified": "vendor",
    "source": "https://www.nvidia.com/en-us/products/workstations/dgx-station/"
  },
  {
    "id": "rx-7900-xtx",
    "name": "Radeon RX 7900 XTX",
    "short": "RX 7900 XTX",
    "vendor": "amd",
    "cls": "consumer",
    "memoryGb": 24,
    "usableGiB": 23.96,
    "basis": "derived",
    "bandwidthGBs": 960,
    "year": 2022,
    "status": "prev-gen",
    "isDefault": true,
    "note": "384-bit 20Gbps",
    "verified": "partial",
    "source": "https://www.sapphiretech.com/en/consumer/21322-01-20g-radeon-rx-7900-xtx-24g-gddr6"
  },
  {
    "id": "rx-9070-xt",
    "name": "Radeon RX 9070 XT",
    "short": "RX 9070 XT",
    "vendor": "amd",
    "cls": "consumer",
    "memoryGb": 16,
    "usableGiB": 15.97,
    "basis": "derived",
    "bandwidthGBs": 640,
    "year": 2025,
    "status": "shipping",
    "note": "256-bit 20Gbps",
    "verified": "partial",
    "source": "https://www.amd.com/en/products/graphics/desktops/radeon/9000-series/amd-radeon-rx-9070xt.html"
  },
  {
    "id": "rx-9070-gre",
    "name": "Radeon RX 9070 GRE",
    "short": "RX 9070 GRE",
    "vendor": "amd",
    "cls": "consumer",
    "memoryGb": 12,
    "usableGiB": 11.98,
    "basis": "derived",
    "bandwidthGBs": 432,
    "year": 2026,
    "status": "shipping",
    "note": "global launch 2026-06-02",
    "verified": "partial",
    "source": "https://www.techpowerup.com/349546/amd-launches-radeon-rx-9070-gre-worldwide-at-usd-550"
  },
  {
    "id": "radeon-pro-w7900",
    "name": "Radeon PRO W7900",
    "short": "PRO W7900",
    "vendor": "amd",
    "cls": "workstation",
    "memoryGb": 48,
    "usableGiB": 47.92,
    "basis": "derived",
    "bandwidthGBs": 864,
    "year": 2023,
    "status": "shipping",
    "note": "not re-fetched this pass",
    "verified": "partial",
    "source": "https://www.amd.com/en/products/graphics/workstations/radeon-pro/w7900.html"
  },
  {
    "id": "radeon-ai-pro-r9700",
    "name": "Radeon AI PRO R9700",
    "short": "AI PRO R9700",
    "vendor": "amd",
    "cls": "workstation",
    "memoryGb": 32,
    "usableGiB": 31.95,
    "basis": "derived",
    "bandwidthGBs": 640,
    "year": 2025,
    "status": "shipping",
    "note": "256-bit",
    "verified": "partial",
    "source": "https://www.amd.com/en/products/graphics/workstations/radeon-ai-pro/ai-9000-series/amd-radeon-ai-pro-r9700.html"
  },
  {
    "id": "mi300x",
    "name": "Instinct MI300X",
    "short": "MI300X",
    "vendor": "amd",
    "cls": "datacenter",
    "memoryGb": 192,
    "usableGiB": 191.69,
    "basis": "smi",
    "bandwidthGBs": 5300,
    "year": 2023,
    "status": "rentable",
    "isDefault": true,
    "note": "rocm-smi 205822885888 B",
    "verified": "vendor",
    "source": "https://lenovopress.lenovo.com/lp1943-thinksystem-amd-mi300x-192gb-750w-8-gpu-board"
  },
  {
    "id": "mi325x",
    "name": "Instinct MI325X",
    "short": "MI325X",
    "vendor": "amd",
    "cls": "datacenter",
    "memoryGb": 256,
    "usableGiB": 255.58,
    "basis": "derived",
    "bandwidthGBs": 6000,
    "year": 2024,
    "status": "rentable",
    "verified": "vendor",
    "source": "https://www.amd.com/content/dam/amd/en/documents/instinct-tech-docs/product-briefs/instinct-mi325x-datasheet.pdf"
  },
  {
    "id": "mi355x",
    "name": "Instinct MI355X",
    "short": "MI355X",
    "vendor": "amd",
    "cls": "datacenter",
    "memoryGb": 288,
    "usableGiB": 287.53,
    "basis": "derived",
    "bandwidthGBs": 8000,
    "year": 2025,
    "status": "rentable",
    "note": "MI350X has the same memory",
    "verified": "vendor",
    "source": "https://www.amd.com/content/dam/amd/en/documents/instinct-tech-docs/product-briefs/amd-instinct-miI355x-platform-brochure.pdf"
  },
  {
    "id": "arc-b580",
    "name": "Arc B580",
    "short": "B580",
    "vendor": "intel",
    "cls": "consumer",
    "memoryGb": 12,
    "usableGiB": 11.98,
    "basis": "derived",
    "bandwidthGBs": 456,
    "year": 2024,
    "status": "shipping",
    "note": "192-bit 19Gbps",
    "verified": "partial",
    "source": "https://www.intel.com/content/www/us/en/products/details/discrete-gpus/arc/desktop/b-series.html"
  },
  {
    "id": "arc-pro-b60",
    "name": "Arc Pro B60",
    "short": "Pro B60",
    "vendor": "intel",
    "cls": "workstation",
    "memoryGb": 24,
    "usableGiB": 23.96,
    "basis": "derived",
    "bandwidthGBs": 456,
    "year": 2025,
    "status": "shipping",
    "note": "192-bit 19Gbps",
    "verified": "vendor",
    "source": "https://www.intel.com/content/www/us/en/products/sku/243916/intel-arc-pro-b60-graphics/specifications.html"
  },
  {
    "id": "arc-pro-b70",
    "name": "Arc Pro B70",
    "short": "Pro B70",
    "vendor": "intel",
    "cls": "workstation",
    "memoryGb": 32,
    "usableGiB": 31.95,
    "basis": "derived",
    "bandwidthGBs": 608,
    "year": 2026,
    "status": "shipping",
    "note": "256-bit; launched 2026-03-25",
    "verified": "vendor",
    "source": "https://www.intel.com/content/www/us/en/products/sku/245797/intel-arc-pro-b70-graphics/specifications.html"
  },
  {
    "id": "mac-mini-m6-32gb",
    "name": "Mac mini M6 32GB",
    "short": "Mac mini M6 32GB",
    "vendor": "apple",
    "cls": "unified",
    "memoryGb": 32,
    "usableGiB": 21.33,
    "basis": "os-default",
    "bandwidthGBs": 170,
    "year": 2026,
    "status": "shipping",
    "ramGiB": 32,
    "maxGiB": 26,
    "note": "16GB config is 153GB/s",
    "verified": "vendor",
    "source": "https://support.apple.com/en-us/128108"
  },
  {
    "id": "mbp-m5-32gb",
    "name": "MacBook Pro M5 32GB",
    "short": "MacBook Pro M5 32GB",
    "vendor": "apple",
    "cls": "unified",
    "memoryGb": 32,
    "usableGiB": 21.33,
    "basis": "os-default",
    "bandwidthGBs": 153,
    "year": 2025,
    "status": "shipping",
    "ramGiB": 32,
    "maxGiB": 26,
    "verified": "partial",
    "source": "https://en.wikipedia.org/wiki/Apple_M5"
  },
  {
    "id": "m5-pro-64gb",
    "name": "Mac mini / MacBook Pro M5 Pro 64GB",
    "short": "Mac mini / MacBook Pro M5 Pro 64GB",
    "vendor": "apple",
    "cls": "unified",
    "memoryGb": 64,
    "usableGiB": 48.0,
    "basis": "os-default",
    "bandwidthGBs": 307,
    "year": 2026,
    "status": "shipping",
    "ramGiB": 64,
    "maxGiB": 56,
    "isDefault": true,
    "verified": "vendor",
    "source": "https://support.apple.com/en-us/128108"
  },
  {
    "id": "m5-max-128gb",
    "name": "MacBook Pro / Mac Studio M5 Max 128GB",
    "short": "MacBook Pro / Mac Studio M5 Max 128GB",
    "vendor": "apple",
    "cls": "unified",
    "memoryGb": 128,
    "usableGiB": 96.0,
    "basis": "os-default",
    "bandwidthGBs": 614,
    "year": 2026,
    "status": "shipping",
    "ramGiB": 128,
    "maxGiB": 116,
    "isDefault": true,
    "note": "40-core GPU",
    "verified": "vendor",
    "source": "https://support.apple.com/en-gb/128107"
  },
  {
    "id": "m5-ultra-256gb",
    "name": "Mac Studio M5 Ultra 256GB",
    "short": "Mac Studio M5 Ultra 256GB",
    "vendor": "apple",
    "cls": "unified",
    "memoryGb": 256,
    "usableGiB": 192.0,
    "basis": "os-default",
    "bandwidthGBs": 1200,
    "year": 2026,
    "status": "shipping",
    "ramGiB": 256,
    "maxGiB": 240,
    "verified": "vendor",
    "source": "https://support.apple.com/en-gb/128107"
  },
  {
    "id": "m5-ultra-512gb",
    "name": "Mac Studio M5 Ultra 512GB",
    "short": "Mac Studio M5 Ultra 512GB",
    "vendor": "apple",
    "cls": "unified",
    "memoryGb": 512,
    "usableGiB": 384.0,
    "basis": "os-default",
    "bandwidthGBs": 1200,
    "year": 2026,
    "status": "ships-late-oct",
    "ramGiB": 512,
    "maxGiB": 496,
    "note": "512GB configuration ships late October 2026",
    "verified": "vendor",
    "source": "https://www.apple.com/newsroom/2026/08/apple-introduces-new-mac-studio-with-m5-max-and-m5-ultra/"
  },
  {
    "id": "m3-ultra-512gb",
    "name": "Mac Studio M3 Ultra 512GB",
    "short": "Mac Studio M3 Ultra 512GB",
    "vendor": "apple",
    "cls": "unified",
    "memoryGb": 512,
    "usableGiB": 384.0,
    "basis": "os-default",
    "bandwidthGBs": 819,
    "year": 2025,
    "status": "prev-gen",
    "ramGiB": 512,
    "maxGiB": 496,
    "isDefault": true,
    "note": "512GB option withdrawn Mar 2026; installed base",
    "verified": "vendor",
    "source": "https://www.apple.com/newsroom/2025/03/apple-reveals-m3-ultra-taking-apple-silicon-to-a-new-extreme/"
  },
  {
    "id": "m4-max-128gb",
    "name": "Mac Studio / MacBook Pro M4 Max 128GB",
    "short": "Mac Studio / MacBook Pro M4 Max 128GB",
    "vendor": "apple",
    "cls": "unified",
    "memoryGb": 128,
    "usableGiB": 96.0,
    "basis": "os-default",
    "bandwidthGBs": 546,
    "year": 2024,
    "status": "prev-gen",
    "ramGiB": 128,
    "maxGiB": 116,
    "verified": "vendor",
    "source": "https://www.apple.com/newsroom/2024/10/apple-introduces-m4-pro-and-m4-max/"
  },
  {
    "id": "m4-pro-64gb",
    "name": "Mac mini M4 Pro 64GB",
    "short": "Mac mini M4 Pro 64GB",
    "vendor": "apple",
    "cls": "unified",
    "memoryGb": 64,
    "usableGiB": 48.0,
    "basis": "os-default",
    "bandwidthGBs": 273,
    "year": 2024,
    "status": "prev-gen",
    "ramGiB": 64,
    "maxGiB": 56,
    "verified": "vendor",
    "source": "https://www.apple.com/newsroom/2024/10/apple-introduces-m4-pro-and-m4-max/"
  },
  {
    "id": "m2-ultra-192gb",
    "name": "Mac Studio M2 Ultra 192GB",
    "short": "Mac Studio M2 Ultra 192GB",
    "vendor": "apple",
    "cls": "unified",
    "memoryGb": 192,
    "usableGiB": 144.0,
    "basis": "os-default",
    "bandwidthGBs": 800,
    "year": 2023,
    "status": "prev-gen",
    "ramGiB": 192,
    "maxGiB": 180,
    "note": "not re-fetched this pass",
    "verified": "partial",
    "source": "https://www.apple.com/newsroom/2023/06/apple-introduces-m2-ultra/"
  },
  {
    "id": "dgx-spark-128gb",
    "name": "DGX Spark (GB10) 128GB",
    "short": "DGX Spark (GB10) 128GB",
    "vendor": "nvidia",
    "cls": "unified",
    "memoryGb": 128,
    "usableGiB": 112,
    "basis": "os-default",
    "bandwidthGBs": 273,
    "year": 2025,
    "status": "shipping",
    "ramGiB": 128,
    "maxGiB": 119,
    "blackwell": true,
    "isDefault": true,
    "note": "no fixed carve-out; ~119GiB OS-visible, ~112 free at idle; nvidia-smi shows memory Not Supported",
    "verified": "vendor",
    "source": "https://docs.nvidia.com/dgx/dgx-spark/hardware.html"
  },
  {
    "id": "jetson-agx-thor",
    "name": "Jetson AGX Thor 128GB",
    "short": "Jetson AGX Thor 128GB",
    "vendor": "nvidia",
    "cls": "unified",
    "memoryGb": 128,
    "usableGiB": 112,
    "basis": "estimate",
    "bandwidthGBs": 273,
    "year": 2025,
    "status": "shipping",
    "ramGiB": 128,
    "maxGiB": 119,
    "blackwell": true,
    "note": "usable assumed like DGX Spark; robotics module",
    "verified": "third-party",
    "source": "https://jetsonhacks.com/2025/09/21/nvidia-jetson-agx-thor-the-new-king-of-embedded/"
  },
  {
    "id": "ryzen-ai-max-395-128gb",
    "name": "Ryzen AI Max+ 395 128GB (Strix Halo)",
    "short": "Ryzen AI Max+ 395 128GB (Strix Halo)",
    "vendor": "amd",
    "cls": "unified",
    "memoryGb": 128,
    "usableGiB": 96,
    "basis": "os-default",
    "bandwidthGBs": 256,
    "year": 2025,
    "status": "shipping",
    "ramGiB": 128,
    "maxGiB": 117,
    "isDefault": true,
    "note": "96GB via VGM (Windows) or raised GTT (Linux); Linux out of the box ~50% (~62GiB); ~117 with gttsize=120000",
    "verified": "vendor",
    "source": "https://rocmdocs.amd.com/en/develop/how-to/system-optimization/strixhalo.html"
  },
  {
    "id": "ryzen-ai-max-pro-495-192gb",
    "name": "Ryzen AI Max+ PRO 495 192GB (Gorgon Halo)",
    "short": "Ryzen AI Max+ PRO 495 192GB (Gorgon Halo)",
    "vendor": "amd",
    "cls": "unified",
    "memoryGb": 192,
    "usableGiB": 160,
    "basis": "vendor-claimed",
    "bandwidthGBs": 273,
    "year": 2026,
    "status": "launched-limited",
    "ramGiB": 192,
    "maxGiB": 160,
    "note": "launched 2026-09-04; Framework ships Nov 2026",
    "verified": "third-party",
    "source": "https://www.notebookcheck.net/AMD-Ryzen-AI-Max-PRO-495-Processor-Benchmarks-and-Specs.1302238.0.html"
  }
];

export const DEVICE_BY_ID: ReadonlyMap<string, Device> = new Map(DEVICES.map((d) => [d.id, d]));

export const DEFAULT_DEVICE_ID = "rtx-4090";

/** Which engines run on a device. */
export function enginesFor(d: Device): ("llamacpp" | "vllm" | "mlx")[] {
  if (d.vendor === "apple") return ["llamacpp", "mlx"];
  if (d.cls === "consumer" || d.vendor === "intel") return ["llamacpp", "vllm"];
  return ["vllm", "llamacpp"];
}

/** The engine people most often run on a device. */
export function defaultEngine(d: Device): "llamacpp" | "vllm" | "mlx" {
  if (d.vendor === "apple") return "mlx";
  if (d.cls === "datacenter") return "vllm";
  return "llamacpp";
}

/** Whether a GPU typically drives a display (consumer and workstation cards). */
export const drivesDisplay = (d: Device) => d.cls === "consumer" || d.cls === "workstation";

/** Smallest-first ladder for "smallest setup that fits" on model pages. */
export const SETUP_LADDER: readonly [string, 1 | 2 | 4 | 8][] = [
  ["rtx-4090", 1],
  ["rtx-5090", 1],
  ["rtx-4090", 2],
  ["rtx-6000-ada", 1],
  ["h100-sxm", 1],
  ["rtx-pro-6000-blackwell", 1],
  ["h100-sxm", 2],
  ["h200-sxm", 1],
  ["h100-sxm", 4],
  ["h200-sxm", 4],
  ["h100-sxm", 8],
  ["h200-sxm", 8],
  ["b200", 8],
];
